/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    C_Breadcrumb: typeof import('./../src/components/global/C_Breadcrumb/index.vue')['default']
    C_Cascade: typeof import('./../src/components/global/C_Cascade/index.vue')['default']
    C_City: typeof import('./../src/components/global/C_City/index.vue')['default']
    C_Date: typeof import('./../src/components/global/C_Date/index.vue')['default']
    C_Editor: typeof import('./../src/components/global/C_Editor/index.vue')['default']
    C_Footer: typeof import('./../src/components/global/C_Footer/index.vue')['default']
    C_Form: typeof import('./../src/components/global/C_Form/index.vue')['default']
    C_FormSearch: typeof import('./../src/components/global/C_FormSearch/index.vue')['default']
    C_Guide: typeof import('./../src/components/global/C_Guide/index.vue')['default']
    C_Header: typeof import('./../src/components/global/C_Header/index.vue')['default']
    C_Icon: typeof import('./../src/components/global/C_Icon/index.vue')['default']
    C_Language: typeof import('./../src/components/global/C_Language/index.vue')['default']
    C_Layout: typeof import('./../src/components/global/C_Layout/index.vue')['default']
    C_Menu: typeof import('./../src/components/global/C_Menu/index.vue')['default']
    C_MenuTop: typeof import('./../src/components/global/C_MenuTop/index.vue')['default']
    C_Notice: typeof import('./../src/components/global/C_Notice/index.vue')['default']
    C_Progress: typeof import('./../src/components/global/C_Progress/index.vue')['default']
    C_Table: typeof import('./../src/components/global/C_Table/index.vue')['default']
    C_TagsView: typeof import('./../src/components/global/C_TagsView/index.vue')['default']
    C_Theme: typeof import('./../src/components/global/C_Theme/index.vue')['default']
    C_Time: typeof import('./../src/components/global/C_Time/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
