/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    C_Container: typeof import('./../src/components/global/C_Container/index.vue')['default']
    C_dgg: typeof import('./../src/components/local/c_dgg.vue')['default']
    C_Form: typeof import('./../src/components/global/C_Form/index.vue')['default']
    C_Icon: typeof import('./../src/components/global/C_Icon/index.vue')['default']
    C_Layout: typeof import('./../src/components/global/C_Layout/index.vue')['default']
    'IconMdi:currencyTwd': typeof import('~icons/mdi/currency-twd')['default']
    'IconMdi:qualityMedium': typeof import('~icons/mdi/quality-medium')['default']
    IconMdiAccountBox: typeof import('~icons/mdi/account-box')['default']
    NBackTop: typeof import('naive-ui')['NBackTop']
    NButton: typeof import('naive-ui')['NButton']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NCheckboxGroup: typeof import('naive-ui')['NCheckboxGroup']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NInput: typeof import('naive-ui')['NInput']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NOption: typeof import('naive-ui')['NOption']
    NSelect: typeof import('naive-ui')['NSelect']
    NSelectOption: typeof import('naive-ui')['NSelectOption']
    NSpace: typeof import('naive-ui')['NSpace']
    NUpload: typeof import('naive-ui')['NUpload']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
