/**
 * 同步版本号脚本
 * 从 package.json 读取版本号并写入到 src/config/version.ts
 */
import { readFileSync, writeFileSync, mkdirSync } from 'fs'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

try {
  // 读取 package.json
  const packageJsonPath = join(__dirname, '../package.json')
  const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf-8'))
  const version = packageJson.version

  // 确保目录存在
  const srcDir = join(__dirname, '../src')
  mkdirSync(srcDir, { recursive: true })

  // 生成 version.ts 内容
  const versionTsContent = `/**
 * Version Configuration
 * Auto-generated by build script, do not modify manually
 */
export const version = '${version}'
`

  // 写入文件
  const versionTsPath = join(srcDir, 'version.ts')
  writeFileSync(versionTsPath, versionTsContent, 'utf-8')

  console.log(`✓ Version synced successfully: ${version}`)
} catch (error) {
  console.error('✗ Version sync failed:', error.message)
  process.exit(1)
}